# Generated by Django 5.0.4 on 2024-11-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=11, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('code', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('dimention', models.CharField(max_length=50)),
                ('warehouse', models.CharField(max_length=50)),
                ('qty_in_wh', models.FloatField()),
                ('price', models.FloatField()),
                ('image_urel', models.URLField(blank=True, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='fileImageData.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(auto_now=True, null=True)),
                ('customer_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_Info', to='fileImageData.customers')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedItem', to='fileImageData.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervizer', to='fileImageData.users')),
            ],
        ),
    ]
