# Generated by Django 5.0.4 on 2024-11-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
