# Generated by Django 5.0.4 on 2024-11-29 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0002_alter_product_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileImageData.productlist')),
            ],
        ),
    ]
