# Generated by Django 5.0.4 on 2024-12-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0003_missingphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedproduct',
            name='invoice',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectedproduct',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Delivered', 'Delivered')], default='Open', max_length=50),
        ),
    ]
