# Generated by Django 5.0.4 on 2024-12-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0004_collectedproduct_invoice_collectedproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedproduct',
            name='date',
            field=models.DateField(auto_now=True),
            preserve_default=False,
        ),
    ]
