# Generated by Django 5.0.4 on 2024-12-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0005_alter_collectedproduct_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedproduct',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Open', max_length=50),
        ),
    ]
