# Generated by Django 5.0.4 on 2024-12-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0008_alter_collectedproduct_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentinvoice',
            old_name='invoice_number',
            new_name='invoice',
        ),
    ]
