# Generated by Django 5.0.4 on 2024-12-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0009_rename_invoice_number_parentinvoice_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedproduct',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectedproduct',
            name='total',
            field=models.FloatField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
