# Generated by Django 5.0.4 on 2024-12-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0010_collectedproduct_price_collectedproduct_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedproduct',
            name='total',
            field=models.FloatField(),
        ),
    ]
