# Generated by Django 5.0.4 on 2024-12-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0011_alter_collectedproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectedproduct',
            name='date',
        ),
        migrations.RemoveField(
            model_name='collectedproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='parentinvoice',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Open', max_length=50),
        ),
    ]
