# Generated by Django 5.0.4 on 2024-12-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0012_remove_collectedproduct_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedproduct',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Missing', 'Missing')], default='Available', max_length=50),
        ),
    ]
