# Generated by Django 5.0.4 on 2024-12-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0013_collectedproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinvoice',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
