# Generated by Django 5.0.4 on 2024-12-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0014_alter_parentinvoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectedproduct',
            name='customer_info',
        ),
        migrations.RemoveField(
            model_name='collectedproduct',
            name='user',
        ),
        migrations.AddField(
            model_name='customers',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentinvoice',
            name='customer_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_Info', to='fileImageData.customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentinvoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervizer', to='fileImageData.users'),
            preserve_default=False,
        ),
    ]
