# Generated by Django 5.0.4 on 2025-01-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0015_remove_collectedproduct_customer_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Valid', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='vizer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parentinvoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
