# Generated by Django 5.0.4 on 2025-01-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileImageData', '0016_users_status_users_vizer_alter_parentinvoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='rar_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
